{{- if .Values.pm.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-manager-deployment
  labels:
    app: proxy-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy-manager
  template:
    metadata:
      labels:
        app: proxy-manager
    spec:
      containers:
        - name: proxy-manager-container
          image: {{ .Values.pm.image.repository }}:{{ .Values.pm.image.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.global.pm_port }}
          env: 
          - name: GIN_MODE
            value: "release"
          - name: PORT
            value: "{{ .Values.global.pm_port }}"
          - name: LOG_PATH
            value: {{ .Values.pm.logpath }}
          - name: LOG_NAME
            value: {{ .Values.pm.logname }}
          - name: LOG_LEVEL
            value: {{ .Values.pm.loglevel }}
          - name: PROXY_LIST_PATH
            value: {{ .Values.pm.filepath }}/{{ .Values.pm.filename }}
          
          volumeMounts:
            - name: proxy-secret
              mountPath: {{ .Values.pm.filepath }}/{{ .Values.pm.filename }}
              subPath: {{ .Values.pm.filename }}
          
      volumes:
        - name: proxy-secret
          secret:
            secretName: {{ .Values.pm.secret_name }}

{{- end }}