{{- if .Values.autoscaling.vertical.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: main-api-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       main-api-deployment
  updatePolicy:
    updateMode: "{{ .Values.autoscaling.vertical.mode }}"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]
{{- end }}  
