{{- if .Values.couriercenter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: couriercenter-tracker-service
spec:
  type: ClusterIP
  selector:
    app: couriercenter-tracker
  ports:
    - protocol: TCP
      port: {{ .Values.global.tracker_port }}
      targetPort: {{ .Values.global.tracker_port }}

{{- end }}