{{- if .Values.skroutz.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: skroutz-tracker-service
spec:
  type: ClusterIP
  selector:
    app: skroutz-tracker
  ports:
    - protocol: TCP
      port: {{ .Values.global.tracker_port }}
      targetPort: {{ .Values.global.tracker_port }}

{{- end }}