apiVersion: v1
kind: Pod
spec:
  containers:
  - name: python
    image: golang:latest
    command:
    - sleep
    args:
    - infinity
    volumeMounts:
    - name: shared-volume
      mountPath: /workspace
  volumes:
  - name: shared-volume
    emptyDir: {}