apiVersion: v1
kind: Pod
spec:
  containers:
  - name: python
    image: python:3.12.1-slim-bullseye
    command:
    - sleep
    args:
    - infinity
    volumeMounts:
    - name: shared-volume
      mountPath: /workspace