{{- if .Values.speedex.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: speedex-tracker-service
spec:
  type: ClusterIP
  selector:
    app: speedex-tracker
  ports:
    - protocol: TCP
      port: {{ .Values.global.tracker_port }}
      targetPort: {{ .Values.global.tracker_port }}

{{- end }}