{{- if .Values.elta.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elta-tracker-deployment
  labels:
    app: elta-tracker
spec:
  replicas: {{ .Values.elta.replicas }}
  selector:
    matchLabels:
      app: elta-tracker
  template:
    metadata:
      labels:
        app: elta-tracker
    spec:
      containers:
      - name: elta-tracker-container
        image: {{ .Values.elta.image.repository }}:{{ .Values.elta.image.tag }}
        imagePullPolicy: Always
        ports:
          - containerPort: {{ .Values.global.tracker_port }}
        resources:
          requests:
            cpu: "40m"
            memory: "50M"
          limits:
            cpu: "60m"
            memory: "80M"
        env:
        - name: PORT
          value: "{{ .Values.global.tracker_port }}"
        - name: LOG_LEVEL
          value: {{ .Values.elta.loglevel }}
        - name: PM_PORT
          value: "{{ .Values.global.pm_port }}"
        - name: USE_PROXY
          value: "{{ .Values.elta.use_proxy }}"

{{- end }}