{{- if .Values.elta.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: elta-tracker-service
spec:
  type: ClusterIP
  selector:
    app: elta-tracker
  ports:
    - protocol: TCP
      port: {{ .Values.global.tracker_port }}
      targetPort: {{ .Values.global.tracker_port }}

{{- end }}