{{- if and .Values.elta.enabled .Values.autoscaling.vertical.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: elta-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       elta-tracker-deployment
  updatePolicy:
    updateMode: "{{ .Values.autoscaling.vertical.mode }}"
  resourcePolicy:
    containerPolicies:
      - containerName: "*"
        controlledResources: ["cpu", "memory"]
{{- end }}
