{{- if .Values.acs.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: acs-tracker-service
spec:
  type: ClusterIP
  selector:
    app: acs-tracker
  ports:
    - protocol: TCP
      port: {{ .Values.global.tracker_port }}
      targetPort: {{ .Values.global.tracker_port }}

{{- end }}