name: ACS Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/acs/**'
  push:
    branches:
      - main
    paths:
      - 'src/acs/**'

jobs:
  # test:
  #   runs-on: self-hosted
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v2
  #   - name: Run tests
  #     run: |
  #       cd src/acs
  #       sh test.sh
    # - name: Cleanup
    #   run: |
    #     cd $GITHUB_WORKSPACE
    #     rm -rf *

  build-upload-dev:
    # needs: test
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./src/acs
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/acs-tracker:${{ github.sha }}

  build-upload-prod:
    needs: build-upload-dev
    runs-on: self-hosted
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        context: ./src/acs
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/acs-tracker:latest
