name: ELTA Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - 'src/elta/**'
  push:
    branches:
      - main
    paths:
      - 'src/elta/**'

jobs:
  test:
    runs-on: self-hosted
    container: python:3.12.2-alpine3.19
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run tests
      run: |
        cd src/elta
        sh test.sh
    - name: Cleanup
      run: |
        cd $GITHUB_WORKSPACE
        rm -rf * .github

  build-upload-dev:
    needs: test
    runs-on: self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        context: ./src/elta
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/elta-tracker:${{ github.sha }}

  build-upload-prod:
    needs: test
    runs-on: self-hosted
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        context: ./src/elta
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/elta-tracker:latest
